export type ReservationRecord = {
  id: string;
  businessId: string;
  customerName: string;
  phone: string | null;
  email: string | null;
  country: string | null;
  language: string | null;
  origin: string | null;
  destination: string | null;
  travelDate: string | null;
  travelTime: string | null;
  flightCode: string | null;
  adultCount: number;
  childCount: number;
  babyCount: number;
  vehicleCategory: string | null;
  vehicleName: string | null;
  assignedVehicle: string | null;
  driverName: string | null;
  pickupStatus: string | null;
  operationNotes: string | null;
  totalAmount: number | null;
  depositAmount: number | null;
  remainingAmount: number | null;
  currency: string | null;
  paymentStatus: string;
  notes: string | null;
  source: string;
  bookingStatus: string;
  message: string;
  status: string;
  createdAt: string;
};

export type ReservationCreateInput = {
  customerName: string;
  phone?: string;
  email?: string;
  country?: string;
  language?: string;
  fromLocation?: string;
  toLocation?: string;
  date?: string;
  time?: string;
  origin?: string;
  destination?: string;
  travelDate?: string;
  travelTime?: string;
  flightCode?: string;
  vehicle?: string;
  total?: number | string;
  deposit?: number | string;
  remaining?: number | string;
  note?: string;
  adultCount?: number | string;
  childCount?: number | string;
  babyCount?: number | string;
  adults?: number | string;
  children?: number | string;
  infants?: number | string;
  vehicleCategory?: string;
  vehicleName?: string;
  assignedVehicle?: string;
  driverName?: string;
  totalAmount?: number | string;
  depositAmount?: number | string;
  remainingAmount?: number | string;
  currency?: string;
  paymentStatus?: string;
  notes?: string;
  source?: string;
  bookingStatus?: string;
  message?: string;
};

export type ReservationUpdateInput = Partial<ReservationCreateInput> & {
  recordId: string;
  assignedVehicle?: string;
  driverName?: string;
  pickupStatus?: string;
  operationNotes?: string;
  totalAmount?: number | string;
  depositAmount?: number | string;
  remainingAmount?: number | string;
};
