export const RESERVATION_LABELS = {
  customerName: "Müşteri adı soyadı",
  phone: "Telefon",
  email: "Mail",
  country: "Ülke",
  language: "Dil",
  from: "Nereden",
  to: "Nereye",
  date: "Tarih",
  time: "Saat",
  flightCode: "Uçuş kodu",
  adults: "Yetişkin",
  children: "Çocuk",
  infants: "Bebek",
  vehicleCategory: "Araç kategorisi",
  vehicleName: "Araç",
  total: "Toplam",
  deposit: "Kapora",
  remaining: "Kalan",
  currency: "Para birimi",
  notes: "Not",
  paymentStatus: "Ödeme durumu",
  status: "Durum",
  voucher: "Voucher",
  create: "Rezervasyon oluştur",
  update: "Güncelle",
  empty: "Henüz rezervasyon yok.",
  previewTitle: "Rezervasyon",
  pageTitle: "Rezervasyonlar",
  pageDescription: "Rezervasyonları oluştur, düzenle ve voucher önizlemesine geç.",
  createSuccess: "Rezervasyon oluşturuldu.",
  updateSuccess: "Rezervasyon güncellendi.",
  createError: "Rezervasyon oluşturulamadı.",
  updateError: "Rezervasyon güncellenemedi.",
  voucherPreview: "Voucher önizleme",
  qrPlaceholder: "QR placeholder",
  noVoucher: "Voucher bulunamadı.",
  loading: "Yükleniyor...",
} as const;

export const RESERVATION_STATUS_OPTIONS = [
  "Bekliyor",
  "Onaylandı",
  "Şoför Atandı",
  "Tamamlandı",
  "İptal",
] as const;

export const RESERVATION_PAYMENT_STATUS_OPTIONS = [
  "Ödenmedi",
  "Kapora Alındı",
  "Ödendi",
  "Araçta Tahsil",
  "İade",
  "İptal",
] as const;

export const RESERVATION_CURRENCY_OPTIONS = [
  "TRY",
  "EUR",
  "USD",
  "GBP",
  "AED",
] as const;
